name: Build

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build Online.js
              run: npm run build:online

            - name: Build ThreadEventHandler.js
              run: npm run build:threadhandler

            - name: Build HTML
              run: npm run build:html

            - name: List build artifacts
              run: ls -lah dist/Web/

            - name: Upload dist artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: robrowser-dist-web
                  path: dist/Web/
                  retention-days: 30

            - name: Run lint (non-blocking)
              run: npm run lint || true
              continue-on-error: true
